navigate, UI login, signup
thaian1234/livestream-app pull request #36
Opened 2024-09-01 03:53 UTC by ThuyTrang003

- navigate login/signup in app/(auth)/
- custom and modify some components/ui
- modify globals.css because it causes an error
- modify page.tsx (check again)
- bun.lockb : self modify
->>> navigate, built UI login, signup
![image](https://github.com/user-attachments/assets/0770f736-3e73-4ab3-a960-6a3a12cb399e)
![image](https://github.com/user-attachments/assets/8af9b043-71d3-4f99-8edf-7ccba6a0ffac)

2024-09-06 07:58 UTC, thaian1234 requested changes

2024-09-06 07:58 UTC, thaian1234 commented on style/auth.css
Không cần điều chỉnh box-sizing (mặc định tailwind đã bỏ r), class container này có bị trùng với container của tailwind không ?

2024-09-06 07:58 UTC, thaian1234 commented on app/(auth)/layout.tsx
Sử dụng thẻ Img  của next thay vì thẻ bình thường nha

2024-09-06 08:37 UTC, thaian1234 requested changes

2024-09-06 08:37 UTC, thaian1234 commented on app/(auth)/signup/page.tsx
Thẻ Card vẫn dính inline css nha, đổi tên folder thành sign-up

2024-09-06 08:37 UTC, thaian1234 commented on app/(auth)/login/page.tsx
Đổi tên folder thành sign-in

2024-09-06 08:37 UTC, thaian1234 commented on components/auth/icon-login.tsx
> +            </div>
Nên sử dụng space-x-4 thay vì thêm className mr-4 cho từng button

2024-09-06 08:37 UTC, thaian1234 commented on app/(auth)/signup/page.tsx
> +        <Card style={{ justifyContent: "space-between" }}  >
inline-css!

2024-09-06 08:37 UTC, thaian1234 commented on components/ui/input.tsx
> +			},
để size bình thường thay vì customSize, file này mình chủ động thay đổi hết.

2024-09-06 08:37 UTC, thaian1234 commented on tailwind.config.ts
> +				red: "#ef4444",
Những màu này mặc định có sẵn rồi, không cần thêm vào

2024-09-06 08:37 UTC, thaian1234 commented on app/(auth)/layout.tsx
> +import "@/style/auth.css"
src="/logoipsum-330.svg" là được r không cần import vào

2024-09-06 11:02 UTC, ThuyTrang003 commented on style/auth.css
t ko biết, nên t cứ sửa tên cho chắc

2024-09-06 11:02 UTC, ThuyTrang003 commented on app/(auth)/login/page.tsx
những chỗ trên UI có chữ login có đổi ko

2024-09-06 11:07 UTC, ThuyTrang003 commented on components/ui/input.tsx
> +			},
cái này nó báo lỗi á, search thì thấy bảo nó có size mặc định

2024-09-06 11:29 UTC, thaian1234 commented on app/(auth)/login/page.tsx
Chỗ nào nó báo lỗi thì chỉnh import lại th

2024-09-06 11:33 UTC, thaian1234 commented on components/ui/input.tsx
> +			},
oke

2024-09-06 11:39 UTC, thaian1234 requested changes

2024-09-06 11:39 UTC, thaian1234 commented on components/ui/button.tsx
> +                gradient: "bg-gradient-to-r bg-gradient-to-r from-teal-1 via-teal-2 to-teal-3",
bg-gradient-to-r đang bị lập 2 lần nè

2024-09-06 11:39 UTC, thaian1234 commented on components/ui/button.tsx
>      {
xài focus-visible:ring-1 thì xóa cái focus-visible:ring-2 đi nha (bị trùng)

2024-09-07 05:22 UTC, thaian1234 approved these changes

2024-09-07 05:23 UTC, merged