add follow api
thaian1234/livestream-app pull request #41
Opened 2024-09-07 09:15 UTC by vanduy352003

2024-09-07 13:44 UTC, thaian1234 requested changes
Parse dữ liệu ở Controller

2024-09-07 13:44 UTC, thaian1234 commented on server/api/controllers/follow.controler.ts
> +                });
Lấy FollowValidation.insert.parse(followings) ở đây nha, trong Repository không nên parse

2024-09-07 13:44 UTC, thaian1234 commented on server/api/controllers/follow.controler.ts
> +                });
đây cũng vậy

2024-09-07 13:44 UTC, thaian1234 commented on server/api/lib/validations/schema.validation.ts
> +        });
ở insertSchema bỏ phần merge và omit đi sẽ không bị lỗi insert nữa. Trên nhánh main mới của t mới viết lại

2024-09-07 13:44 UTC, thaian1234 commented on server/api/lib/validations/schema.validation.ts
> +        following: UserValidation.selectSchema.omit({ bio: true }),
sao omit bio vậy ông ?. Tái sử dụng baseSchema

2024-09-07 13:44 UTC, thaian1234 commented on server/api/repositories/follow.repository.ts
> +            return FollowValidation.parseFollowingMany(followings);
Parse ở tầng Controller nha

2024-09-07 13:44 UTC, thaian1234 commented on server/api/repositories/follow.repository.ts
> +            return FollowValidation.parseFollowerMany(followers);
Đây cũng v

2024-09-07 13:44 UTC, thaian1234 commented on server/api/repositories/follow.repository.ts
> +                limit: 10,
chuẩn bị sẵn offset và limit sau này làm phân trang nè. Trên hàm findRecommendByUserId(userId: string, offset?:number = 0, limit?:number = 10)

2024-09-07 13:44 UTC, thaian1234 commented on server/api/services/follow.service.ts
> +import { use } from "react";
bỏ import này đi

2024-09-07 13:44 UTC, thaian1234 commented on server/api/controllers/follow.controler.ts
> +    }
Quên check trường hợp user tự follow chính mình !!!!

2024-09-07 13:44 UTC, thaian1234 commented on server/api/controllers/follow.controler.ts
> +    }
Quên check trường hợp user tự Unfollow chính mình

2024-09-07 13:44 UTC, thaian1234 commented on server/api/lib/validations/schema.validation.ts
> +    });
sao khúc này không từ base.extend ra thêm follower ? Tái sử dụng lại cái baseSchema nha

2024-09-07 13:49 UTC, vanduy352003 commented on server/api/lib/validations/schema.validation.ts
> +        following: UserValidation.selectSchema.omit({ bio: true }),
tại lấy danh sách follower/following để hiện thị tui thấy đâu cần hiện bio đâu đúng ko ông

2024-09-07 13:49 UTC, vanduy352003 commented on server/api/lib/validations/schema.validation.ts
> +        });
ông bị lỗi hả ông ảo vậy

2024-09-07 14:05 UTC, thaian1234 commented on server/api/lib/validations/schema.validation.ts
> +        following: UserValidation.selectSchema.omit({ bio: true }),
oke ông

2024-09-07 14:06 UTC, thaian1234 commented on server/api/lib/validations/schema.validation.ts
> +        });
Optimize lại thôi ông, có sẵn baseSchema rồi mình extend hoặc overide lại, riêng mấy thằng insert thì đừng merge là đc

2024-09-07 14:10 UTC, vanduy352003 commented on server/api/lib/validations/schema.validation.ts
> +    });
okkkkkkkkkk ông

2024-09-07 14:10 UTC, vanduy352003 commented on server/api/controllers/follow.controler.ts
> +    }
okkkkkkkkkk ông

2024-09-07 14:10 UTC, vanduy352003 commented on server/api/controllers/follow.controler.ts
> +    }
okkkkkkkkkk ông

2024-09-07 14:12 UTC, vanduy352003 commented on server/api/repositories/follow.repository.ts
> +                limit: 10,
okkkkkkkkkk ông

2024-09-07 14:13 UTC, vanduy352003 commented on server/api/repositories/follow.repository.ts
> +            return FollowValidation.parseFollowerMany(followers);
okkkkkkkkkk ông

2024-09-07 14:14 UTC, vanduy352003 commented on server/api/repositories/follow.repository.ts
> +            return FollowValidation.parseFollowingMany(followings);
okkkkkkkkkk ông

2024-09-07 14:14 UTC, vanduy352003 commented on server/api/controllers/follow.controler.ts
> +                });
okkkkkkkkkk ông

2024-09-07 14:14 UTC, vanduy352003 commented on server/api/controllers/follow.controler.ts
> +                });
okkkkkkkkkk ông

2024-09-07 14:23 UTC, vanduy352003 commented on server/api/lib/validations/schema.validation.ts
> +        });
khúc này ông làm sao để nó bị lỗi thế ông, tui thử mà ko thấy nó lỗi

2024-09-07 14:25 UTC, vanduy352003 commented on server/api/repositories/follow.repository.ts
> +                limit: 10,
à mà vậy danh sách follower với following cần phân trang luôn không

2024-09-07 14:28 UTC, vanduy352003 commented on server/api/lib/validations/schema.validation.ts
> +        });
okkkkk ông

2024-09-08 03:40 UTC, thaian1234 requested changes
Oke ổn r đó ông, sửa lại mấy cái t mới cmt là oke

2024-09-08 03:40 UTC, thaian1234 commented on server/api/controllers/follow.controler.ts
> +                const limitNumber = limit ? parseInt(limit, 10) : 10;
Sử dụng zValidator('query') nha ông, tránh trường hợp người ta nhập số âm nữa hoặc nhập chuỗi.
![image](https://github.com/user-attachments/assets/0caddc07-8e9b-4c2a-b48c-a0d7fe7c809a)

2024-09-08 03:40 UTC, thaian1234 commented on server/api/controllers/follow.controler.ts
> +                const limitNumber = limit ? parseInt(limit, 10) : 10;
Sửa lại limit, offset giống như trên

2024-09-08 03:40 UTC, thaian1234 commented on server/api/controllers/follow.controler.ts
> +                const limitNumber = limit ? parseInt(limit, 10) : 10;
Sửa lại limit, offset giống như trên

2024-09-08 03:40 UTC, thaian1234 commented on server/api/lib/validations/schema.validation.ts
> +    public static deleteSchema = this.insertSchema;
Sửa lại deleteSchema cho đúng nè
![image](https://github.com/user-attachments/assets/16902eec-5ba9-4e7e-9b6e-3cc7629c7e00)

2024-09-08 04:40 UTC, vanduy352003 commented on server/api/controllers/follow.controler.ts
> +                const limitNumber = limit ? parseInt(limit, 10) : 10;
changed

2024-09-08 04:40 UTC, vanduy352003 commented on server/api/controllers/follow.controler.ts
> +                const limitNumber = limit ? parseInt(limit, 10) : 10;
changed

2024-09-08 04:40 UTC, vanduy352003 commented on server/api/controllers/follow.controler.ts
> +                const limitNumber = limit ? parseInt(limit, 10) : 10;
changed

2024-09-08 04:40 UTC, vanduy352003 commented on server/api/lib/validations/schema.validation.ts
> +    public static deleteSchema = this.insertSchema;
changed

2024-09-08 08:17 UTC, thaian1234 approved these changes
ok

2024-09-08 08:17 UTC, merged