update find follower and following, fix forget parsing user info
thaian1234/livestream-app pull request #56
Opened 2024-09-22 06:45 UTC by vanduy352003

forget to create pull request

2024-09-22 15:01 UTC, thaian1234 requested changes

2024-09-22 15:01 UTC, thaian1234 commented on server/api/controllers/follow.controller.ts
Có lỗi chỗ này, lỡ như không tìm thấy 1 recommended nào thì API này sẽ trả về Bad Request --> Không cần phải check vì nếu không có Recommend thì ở dưới Client sẽ nhận được Status.Ok và không có dữ liệu của Recommend
![image](https://github.com/user-attachments/assets/18fe584b-7823-4a18-a1f1-ee561cd8d7d3)

2024-09-22 15:09 UTC, vanduy352003 commented on server/api/controllers/follow.controller.ts
đã xóa ông

2024-09-23 02:07 UTC, thaian1234 approved these changes
LGTM

2024-09-23 02:07 UTC, merged